### ISSUE TITLE
Help on Castle::track

### ISSUE THREAD

**Issue by reyphilipregis** [castle/castle-php#15]
Hi guys, I need your help. I'm using this castle-php library for my project and I have a problem. I already followed the documentation here https://castle.io/docs/events for PHP but still I can't log events in my castle. I tried creating a file just to isolate and just run castle and here's my code. The problem here is that I have an error which asks for headers but its said in the documentation that headers are set automatically for server side SDK's like PHP.

Here's the error message: 

`[01-Jun-2017 06:31:51 Europe/Athens] PHP Fatal error:  Uncaught exception 'Castle_BadRequest' with message 'One or more HTTP headers are missing: 
header 'X-Castle-Cookie-Id' is missing' in /home/stgngstm/public_html/stm-libraries/castle-php/lib/Castle/Request.php:81
Stack trace:
#0 /home/stgngstm/public_html/stm-libraries/castle-php/lib/Castle/Request.php(116): Castle_Request->handleApiError(Array, 400)
#1 /home/stgngstm/public_html/stm-libraries/castle-php/lib/Castle/Request.php(162): Castle_Request->handleResponse(Object(Castle_RequestTransport))
#2 /home/stgngstm/public_html/stm-libraries/castle-php/lib/Castle/Castle.php(101): Castle_Request->send('post', '/track', Array)
#3 /home/stgngstm/public_html/info.php(25): Castle::track(Array)
#4 {main}
  thrown in /home/stgngstm/public_html/stm-libraries/castle-php/lib/Castle/Request.php on line 81
`

Here's my Code:

`<?php
    require_once $_SERVER['DOCUMENT_ROOT'].'/stm-libraries/castle-php/lib/Castle.php';

    Castle::setApiKey('myapikeyhere');

    $verdict = Castle::authenticate(array(
	  'name' => '$login.succeeded',
	  'user_id' => '20007a'
	));

	if ($verdict->action == 'allow') {
		echo 'Allowed';
	  
		Castle::identify('20007a', array(
	      'traits' => array(
	      	'name' => 'Rey Philip Regis',
	      	'_region' => 'NCR',
	      	'email' => 'reyphilipregis@hotmail.com'
	      )
	    ));

	    Castle::track(array(
		  'name' => 'My important event',
		  'user_id' => '20007a'
		));

	} else if ($verdict->action == 'challenge') {
	  // Additional authentication required
		echo 'Challenge';
	} else if ($verdict->action == 'deny') {
		echo 'Denied';
	  // Failed authentication. Lock account
	}
?>`

Hope you guys can help me. Thanks.

**Comment by reyphilipregis** [comment]
I added this code at the top of the page and now I don't receive any errors but still the event wont display on my user's events page in castle.io. I really dont know why it doesn't log. Castle::identify is working but Castle::track doesn't.

`header('X-Castle-Cookie-Id: 83b9fb1f-8efa-4c93-bc42-6cc62b43f6a9');
header('X-Castle-Ip: '.$_SERVER['SERVER_ADDR']);
header('X-Castle-Headers: {"User-Agent": "Mozilla/5.0 (Windows NT 6.3; Trident/7.0; rv:11.0) like Gecko", "Accept": "text/html", "Accept-Language": "en-us,en;q=0.5"}');`

**Comment by wallin** [comment]
Hey @reyphilipregis. Thanks for reporting. We'll have a look ASAP.

**Comment by reyphilipregis** [comment]
@wallin I solved the header problems aleady but I need to manually set them at the top. The only reason it doesnt track is because my IP in castle is blocked. So what I did is unblock it and now its successfully logging. 

Now I have a new problem, do you know why this is happening?

`28: Resolving timed out after 3512 milliseconds on line 101 in /home/stmforum/public_html/stm-libraries/castle-php/lib/Castle/Request.php
#0 /home/stmforum/public_html/stm-libraries/castle-php/lib/Castle/Request.php(107): Castle_Request->handleRequestError(Object(Castle_RequestTransport))
#1 /home/stmforum/public_html/stm-libraries/castle-php/lib/Castle/Request.php(162): Castle_Request->handleResponse(Object(Castle_RequestTransport))
#2 /home/stmforum/public_html/stm-libraries/castle-php/lib/Castle/Castle.php(89): Castle_Request->send('post', '/identify', Array)
#3 /home/stmforum/public_html/forum/forum.php(891): Castle::identify('21640', Array)
#4 /home/stmforum/public_html/forum/index.php(43): require('/home/stmforum/...')
#5 {main}`

Are there any ways to solve this? Thanks.

**Comment by reyphilipregis** [comment]
@wallin I found another problem again. It says One or more parameters are invalid name missing on Line 93 castle/castle-php/Castle/Request.php

Here's a screenshot:
![downloadjpeg](https://cloud.githubusercontent.com/assets/5327494/26765831/af6733cc-49b6-11e7-977c-f044d99937c1.jpg)

It really is weird, cause sometimes it appears and sometimes it doesn't, its inconsistent.
my code is like this

`Castle::setApiKey(apikeyhere);
Castle::track(array(
	'name'       => 'nameOfEvent',
	'user_id'    => $id,
	'properties' => $props
));`

Can you tell me what I'am doing wrong? Thanks.

**Comment by wallin** [comment]
Hey, we're release a new version https://github.com/castle/castle-php/releases/tag/1.4.2
Could you see if that solves your problem?

**Comment by reyphilipregis** [comment]
I will test it and will give you a feedback if that new version solved all the problems. Thanks.

**Comment by reyphilipregis** [comment]
@wallin code looks good because I will not declare the headers manually. But now I have Operation timedout problem. Do you have any idea to solve this problem? It happens sometimes though. Thanks.
![screen shot 2017-06-20 at 4 04 22 pm](https://user-images.githubusercontent.com/5327494/27322943-69bd7426-55d2-11e7-86c6-671cd72c7a8f.png)

**Comment by wallin** [comment]
Hey @reyphilipregis, is this still an issue for you? Can I close this?
