### ISSUE TITLE
Composer doesn't load in classes.

### ISSUE THREAD

**Issue by tankerkiller125** [castle/castle-php#6]
I have composer setup and working correctly. I am using the dev-master version simply for testing purposes and every single time I get the following error.

Class 'Castle' not found

Looking through the composer auto-load files I have come to the conclusion that the composer.json is not set correctly.

**Comment by wallin** [comment]
Thanks for reporting. I'll have a look

**Comment by wallin** [comment]
I've added `autoload` to the composer file. Could you please confirm that it works on your end as well?
I'll release a new version after that

**Comment by tankerkiller125** [comment]
I can confirm that it works. Of course the API itself doesn't work yet but its nice to know that the lib/SDK does :)

**Comment by wallin** [comment]
Thanks! I'll push a new version
