### ISSUE TITLE
Use an autoloader instead of manually including each file.

### ISSUE THREAD

**Issue by tankerkiller125** [castle/castle-php#8]
You could use an autoloader on lib/Castle.php this is very easy todo.

lib/Castle/autoloader.php

``` php
<?php
/**
 * Get all files from the lib directory and require them.
 */
function getFiles() 
{
    $files = array_diff(scandir(dirname(__FILE__)), array('..', '.'));
    foreach($files as $file)
    {
        require($file);
    }
}
spl_autload_register('getFiles');
```

lib/Castle/Castle.php

``` php
// Everything above requires remain the same
require(dirname(__FILE__) . '/autoloader.php');
// All other requires can be removed.
```

This should greatly reduce the amount of effort needed to maintain this lib.

Another valid way of doing this (even easier) would be to use the following code in place of all the requires

``` php
require(dirname(dirname(__FILE__)) . "/vendor/autoload.php");
```

Thus using composer.

**Comment by JavaPortals** [comment]
While the idea of an auto loader is great. The first example poses a security risk as it would load all PHP files in the specified directory.
